REQUEST HB_CODEPAGE_UTF8EX
PROCEDURE MAIN()
LOCAL N1, N2, N3 AS NUMERIC

    HB_CDPSELECT( "UTF8EX" )
    INPUT "DIGITE O 1° NÚMERO: " TO N1
    INPUT "DIGITE O 2° NÚMERO: " TO N2
    INPUT "DIGITE O 3° NÚMERO: " TO N3
    ? " "
    ? "A SOMA DOS 3 NÚMERO É: ", N1 + N2 + N3
RETURN